# CustomChunkLimit by Dimianas#4303
# All materials:
# https://papermc.io/javadocs/paper/1.12/org/bukkit/Material.html
# https://papermc.io/javadocs/paper/1.13/org/bukkit/Material.html
# https://papermc.io/javadocs/paper/1.14/org/bukkit/Material.html
# https://papermc.io/javadocs/paper/1.15/org/bukkit/Material.html
# https://papermc.io/javadocs/paper/1.16/org/bukkit/Material.html
# https://papermc.io/javadocs/paper/1.17/org/bukkit/Material.html
# https://papermc.io/javadocs/paper/1.18/org/bukkit/Material.html
# https://papermc.io/javadocs/paper/1.19/org/bukkit/Material.html

enable: true   #Enable or disable block limit on server
block-limit:
  redstone_wire: 64
  piston: 128
  sticky_piston: 128
  redstone_block: 256