name: CustomChunkLimit
version: '1.0-SNAPSHOT'
main: ru.customchunklimit.Main
api-version: 1.16
authors: [ Dimianas ]
description: This plugin create for custom limit all block per chunk
website: https://2k2f.site/
